# Generated by Django 4.2.13 on 2024-05-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('texture', models.CharField(max_length=255)),
                ('whatsapp', models.IntegerField()),
                ('volume', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('scalp', models.CharField(max_length=255)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('combinghair', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('cut', models.CharField(max_length=255)),
                ('heat', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=255)),
                ('hairtangle', models.CharField(max_length=255)),
                ('oil', models.CharField(max_length=255)),
                ('hairfall', models.CharField(max_length=255)),
                ('shampoo', models.CharField(max_length=255)),
                ('oilweek', models.CharField(max_length=255)),
                ('conditioner', models.CharField(max_length=255)),
                ('haircomb', models.CharField(max_length=255)),
                ('hairwash', models.CharField(max_length=255)),
                ('chemicaltreatment', models.CharField(max_length=255)),
                ('hairdry', models.CharField(max_length=255)),
                ('treatment', models.CharField(max_length=255)),
            ],
        ),
    ]
